---

- name: Set endpoint
  retries: "{{ retry_count | default(5) }}"
  delay: "{{ task_delay | default(60) }}"
  register: result
  until: result is not failed
  ansible.builtin.command:
    cmd: pvesh create /cluster/notifications/endpoints/smtp --author {{ item.author | quote  }} --from-address {{ item.email_from }} --name {{ item.name | quote }} --server {{ item.server }} --mailto-user {{ item.mailto }} --mode insecure --port 25

- name: Test endpoint
  when: test_endpoint | default(false)
  retries: "{{ retry_count | default(5) }}"
  delay: "{{ task_delay | default(60) }}"
  register: result
  until: result is not failed
  ansible.builtin.command:
    cmd: pvesh create /cluster/notifications/targets/{{ item.name }}/test