---

- name: Set backup-failures
  retries: "{{ retry_count | default(5) }}"
  delay: "{{ task_delay | default(60) }}"
  register: result
  until: result is not failed
  ansible.builtin.command:
    cmd: pvesh create /cluster/notifications/matchers --name {{ item.name | quote }} --comment {{ item.comment | quote  }} --match-field {{ item.match }} --match-severity {{ item.severity }} --mode {{ item.mode }} --target {{ item.target | quote }}
