---

- name: Set endpoint
  retries: "{{ retry_count | default(5) }}"
  delay: "{{ task_delay | default(60) }}"
  register: result
  until: result is not failed
  ansible.builtin.command:
    pvesh create /cluster/notifications/endpoints/smtp --author {{ item.author }} --from-address {{ item.email_from }} --name {{ item.name }} --server {{ item.server }} --mailto-user {{ item.mailto }} --mode insecure --port 25