- name: Set Dualog backup-failures
  retries: "{{ retry_count | default(5) }}"
  delay: "{{ task_delay | default(60) }}"
  register: result
  until: result is not failed
  ansible.builtin.command:
    pvesh create /cluster/notifications/matchers --name {{ item.name }} --comment {{ item.comment }} --match-field {{ item.match }} --match-severity {{ item.severity }} --mode {{ item.mode }} --target {{ item.target }}
